http:
  build: ..
  ports:
   - "8031:80"
  volumes:
    - "../dist:/usr/share/nginx/html"
  dns:
   - 8.8.8.8
   - 8.8.4.4

watch:
  image: mklimuk/jekyll
  volumes:
    - "../:/app"
  dns:
   - 8.8.8.8
   - 8.8.4.4
  command:
    "gulp watch"
